### PR TITLE
feat(list): add Lerna `list` as optional command, closes #170

### PR DESCRIPTION
**Pull request by ghiscoding**
## Description
Add Lerna's [`list`](https://github.com/lerna/lerna/tree/main/commands/list) command as an optional command

## Motivation and Context
closes #170

## How Has This Been Tested?
same as Lerna

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by petermetz** [comment]
+1 we need this as well.

@ghiscoding Do you happen to have this branch published on some alternative package name in npm for those eager to have this working?

cc: @johnhomantaring

**Comment by ghiscoding** [comment]
no, I only maintain one `main` branch to publish 😁, I'm a little bit stuck waiting for another PR #168 to be updated by its author that I really want to be merge and haven't heard back for a week and a half, if I don't hear back by the end of this week then I might try to play some magic and force a merge (there are now merge conflicts in that PR because it's been opened for too long on a branch that I don't own, so I would rather have the author fix the PR if he comes back). I could also skip that PR but like I said, I really wish to have it included in the next release, so we'll see by the end of the week. You can expect a release by early next week. I have other PRs waiting as well for the same reason

**Comment by ghiscoding** [comment]
Now released under [v1.4.0](https://github.com/ghiscoding/lerna-lite/releases/tag/v1.4.0)

**Comment by ghiscoding** [comment]
@petermetz 
It seems that even though you guys pushed me to release this quickly (Lerna-Lite `list`), you guys still aren't using it 1 month later, what's taking you guys so long? 😝 Just teasing here and hope you end up using it soon 😉

**Pull request merged**
