### PR TITLE
fix(version): include the updated root package-lock.json file in commits

### LINKED ISSUE #146: When using the version (or publish) command, the updated root package-lock.json file is not commited
### Describe the bug

When using the `version` (or `publish`) command, the root `package-lock.json` file is correctly updated, but it's not added to the created git commit.

I believe that the problem is due to the promise chaining for updating the lock file is not set up correctly. In the logs, you can see that the adding of the changed files actually happens before the root lock file is updated:

```
lerna-lite sill gitAdd [
lerna-lite sill gitAdd   'packages/<package-1>/package.json',
lerna-lite sill gitAdd   'packages/<package-1>/CHANGELOG.md',
lerna-lite sill gitAdd   'packages/<package-2>/package.json',
lerna-lite sill gitAdd   'packages/<package-2>/CHANGELOG.md'
lerna-lite sill gitAdd ]
lerna-lite sill gitCommit chore(release): publish
lerna-lite sill gitCommit
lerna-lite sill gitCommit  - @<org>/<package-1>@3.4.112
lerna-lite sill gitCommit  - @<org>/<package-2>@9.4.168
lerna-lite verb git commit -F /tmp/c95d05df-4db1-40c6-a552-226d58894283/lerna-commit.txt
lerna-lite sill lock updating root "package-lock-json" for package "@<org>/<package-1>"
lerna-lite sill lock updating root "package-lock-json" for package "@<org>/<package-2>"
```

### Reproduction

Do the following in a repo using lerna-lite, npm >= 7, and npm workspaces
* Make some changes in one of the packages and commit them
* Run `npx lerna version --no-push`
* Observe that the `package-lock.json` file at the root has been updated, but the changes are not part of the commit made by lerna-lite (i.e., there are now uncommited changes in that file)

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "npm",
  "command": {
    "publish": {
      "ignoreChanges": ["README.md"],
      "conventionalCommits": true,
      "message": "chore(release): publish",
      "registry": "<our internal registry>"
    }
  },
  "packages": ["packages/*"],
  "version": "independent"
}

```
</p></details>

### Environment Info

```shell
| Executable        | Version  |
| ----------------- | -------- |
| `lerna --version` | 1.1.1    |
| `npm --version`   | 8.5.0    |
| `node --version`  | v16.14.2 |
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/lerna-lite/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/ghiscoding/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by ghost91-**
Fixes #146.

Ideally, a corresponding test should also be added, but I don't have enough knowledge about the internals and how tests are written for lerna-lite to be able to write such a test myself.

### CODE REVIEW

**Comment by ghiscoding** [comment]
@ghost91- 
The test is [here](https://github.com/ghiscoding/lerna-lite/blob/main/packages/version/src/__tests__/update-lockfile-version.spec.js#L59), do you want to give a quick look and see if you can add a test before I merge this?

**Comment by ghost91-** [comment]
The problem is related to how the different promise calls were orchestrated, and when files were being added to be committed. I don't think it's easily possible to adjust this particular test, since it does the orchestration itself (in a different way, by the way). And it doesn't even commit anything, so it's not possible to check for the problem.

So even with this, I have absolutely no clue how to test this. I think it would probably fit better in https://github.com/ghiscoding/lerna-lite/blob/main/packages/version/src/__tests__/version-command.spec.ts, since the bug occurred in the version command itself (not one of the helper functions). Probably https://github.com/ghiscoding/lerna-lite/blob/main/packages/version/src/__tests__/version-command.spec.ts#L807 is the right test case. But I have no clue how I would test if there are any uncommitted files (the package-lock.json)

**Comment by ghiscoding** [comment]
@ghost91- 
as long as you have at least tested it locally and it fixed the issue you detected then I'm fine with accepting it as is, and all the unit test are still passing so it should be fine for now.

**Comment by ghost91-** [comment]
Yeah, I tested it thoroughly. With this change, all is good. Thanks for merging it so quickly. The files not being commuted created quite a bit of noise in our automated release process. With this, it will be smooth sailing :)

Thanks a lot on general for picking this project up. I understand it’s a lot of work, and you can also only do so much. But it’s really helping us! If I find the time, I’ll try to contribute back a little (if there is something that’s easy enough for me to handle).

**Comment by ghiscoding** [comment]
> Thanks a lot in general for picking this project up. I understand it’s a lot of work, and you can also only do so much. But it’s really helping us! If I find the time, I’ll try to contribute back a little (if there is something that’s easy enough for me to handle).

Yeah it's a challenge for sure, I also don't understand all of the code and I made sure to mention that in a few places in the readme so that people don't get their expectation too high. 😉. Anyway I think my main goal was achieve by updating all dependencies and I also more it more modular by having some commands as optional, so I think it's a win win 😃 

The code that you modified was actually my own contribution to deal with the lock file in this very own repo so apart from this little bug it's nice to see that it works for others too

Thanks for the contribution & feedback, I'm not exactly sure when I'll release this but it should within the next few days. 
Cheers

**Comment by ghiscoding** [comment]
released under [1.2.0](https://github.com/ghiscoding/lerna-lite/releases/tag/v1.2.0)

**Pull request merged**
